@server = https://maryoriesp-redesigned-enigma-x59xw7qrwjjh6j97-8080.preview.app.github.dev
@emp = {{server}}/api/instrumento
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "nombre": "Bateria",
    "categoria": "Percusion",
    "descripcion": "de 8 a 10 tambores con platillos"
}